services:
  nats:
    container_name: cryptoviz/broker:develop
    image: nats:latest
    restart: always
    ports:
      - '4222:4222' # NATS client connections
      - '4223:4223' # WebSocket connections
      - '8222:8222' # HTTP monitoring
    volumes:
      - ./nats-local/nats_config.json:/etc/nats/nats_config.json # Mount a configuration file
      - nats_data:/data/nats                                     # Mount a volume for JetStream data storage
    command: -c /etc/nats/nats_config.json
    networks:
      - app-network

networks:
  app-network:

volumes:
  nats_data:
