apiVersion: v1
kind: ConfigMap
metadata:
  name: staging-nats-crzcommon-configmap
  namespace: staging-nats
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    host: "0.0.0.0"
    port: 4222
    debug: true
    trace: true
    logtime: true

    accounts: {
      admin: {
        jetstream: enabled
        users: [
          { nkey: "UDXU4RCSJNZOIQHZNWXHXORDPRTGNJAHAHFRGZNEEJCPQTT2M7NLCNF4" }
        ]
      }
    }

    jetstream: {
      max_mem: 2GB,
      max_file: 500GB,
      store_dir: "/data/nats"
    }

    tls: {
      cert_file: "/etc/nats/certs/tls.crt"
      key_file: "/etc/nats/certs/tls.key"
      verify_and_map: false
      verify: false
    }

    websocket: {
      port: 443
      no_tls: false
      same_origin: true
      allowed_origins [
        "https://staging.crzgames.com"
      ]
      tls: {
        cert_file: "/etc/nats/certs/tls.crt"
        key_file: "/etc/nats/certs/tls.key"
        verify_and_map: false
        verify: false
      }
    }

    http_port: 8222