apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-nats-crzcommon-pv
  namespace: prod-nats
spec:
  capacity:
    storage: 1500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nats-storage
  hostPath:
    path: /data/nats
