apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staging-nats-crzcommon-pvc
  namespace: staging-nats
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nats-storage
  resources:
    requests:
      storage: 500Gi
