apiVersion: v1
kind: PersistentVolume
metadata:
  name: staging-nats-crzcommon-pv
  namespace: staging-nats
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nats-storage
  hostPath:
    path: /data/nats
